// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using seedDbApp.Data;

#nullable disable

namespace seedDbApp.Migrations
{
    [DbContext(typeof(seedDbAppContext))]
    partial class seedDbAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("seedDbApp.Models.Mobile", b =>
                {
                    b.Property<int>("MobileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MobileId"), 1L, 1);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MobileId");

                    b.ToTable("Mobile");

                    b.HasData(
                        new
                        {
                            MobileId = 1,
                            Model = "Iphone1",
                            Price = 800m
                        },
                        new
                        {
                            MobileId = 2,
                            Model = "Iphone2",
                            Price = 700m
                        },
                        new
                        {
                            MobileId = 3,
                            Model = "Iphone3",
                            Price = 650m
                        },
                        new
                        {
                            MobileId = 4,
                            Model = "Iphone4",
                            Price = 750m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
